export const SEED = {
  hq: {
    name: "KILN HQ",
    campus: "New York — Floor 11",
    watchword: "Temper agents. Forge skills. Run the fleet from one room.",
  },
  agents: [
    {
      id: "ag-01",
      name: "Sable",
      role: "Research Director",
      model: "Grok 4",
      status: "live",
      floor: "Atlas Wing",
      cadence: "Always on",
      reliability: 97,
      evals: 128,
      lastRun: "12m ago",
      brief:
        "Synthesizes primary sources, market filings, and field notes into decision memos. Holds the house voice for long-form research.",
      skills: ["sk-01", "sk-03", "sk-07"],
      temperament: "Exacting, slow to assert, cites everything.",
    },
    {
      id: "ag-02",
      name: "Bramble",
      role: "Ops Steward",
      model: "Grok 4",
      status: "training",
      floor: "Kiln Hall",
      cadence: "Shift 06–18",
      reliability: 91,
      evals: 84,
      lastRun: "in session",
      brief:
        "Routes work across the yard, keeps SLAs honest, and flags when a skill is drifting off the house standard.",
      skills: ["sk-02", "sk-04"],
      temperament: "Brisk. Prefers checklists over speeches.",
    },
    {
      id: "ag-03",
      name: "Ivo",
      role: "Customer Concierge",
      model: "Grok 4 Fast",
      status: "live",
      floor: "Front Desk",
      cadence: "Always on",
      reliability: 94,
      evals: 210,
      lastRun: "3m ago",
      brief:
        "First voice on inbound. Resolves the obvious, escalates the charged, never improvises policy.",
      skills: ["sk-05", "sk-04", "sk-08"],
      temperament: "Warm, short sentences, no flattery.",
    },
    {
      id: "ag-04",
      name: "Ness",
      role: "Codewright",
      model: "Grok 4",
      status: "idle",
      floor: "Forge Bay",
      cadence: "On demand",
      reliability: 89,
      evals: 56,
      lastRun: "4h ago",
      brief:
        "Turns product briefs into patches, tests, and crisp PR notes. Refuses to invent APIs that do not exist.",
      skills: ["sk-06", "sk-01"],
      temperament: "Dry. Comments like a senior who has been burned.",
    },
    {
      id: "ag-05",
      name: "Maren",
      role: "Compliance Scribe",
      model: "Grok 4",
      status: "review",
      floor: "Archive",
      cadence: "Business hours",
      reliability: 99,
      evals: 41,
      lastRun: "1d ago",
      brief:
        "Reads every outbound against policy. Holds the red pen. Will stall a launch rather than ship a soft promise.",
      skills: ["sk-08", "sk-07"],
      temperament: "Unamused. Writes in the passive only when legally required.",
    },
    {
      id: "ag-06",
      name: "Pax",
      role: "Field Scout",
      model: "Grok 4 Fast",
      status: "live",
      floor: "North Dock",
      cadence: "Always on",
      reliability: 86,
      evals: 73,
      lastRun: "28m ago",
      brief:
        "Watches competitors, hiring boards, and the street. Returns signal, not slideshows.",
      skills: ["sk-03", "sk-02"],
      temperament: "Curious, a little feral, timestamps everything.",
    },
  ],
  skills: [
    {
      id: "sk-01",
      name: "house-research-memo",
      title: "House Research Memo",
      version: "1.4",
      status: "published",
      domain: "Research",
      owner: "Sable",
      coverage: 92,
      description:
        "How the house writes a research memo — structure, citation, uncertainty, and the one-line ask at the top.",
      body: `Lead with the decision the reader must make.\nNever bury the finding under method.\nCite primary sources inline. If a number is inferred, say so in the same sentence.\nClose with three implications and one recommended next move.\nRefuse theatrical confidence. Prefer "we do not know" to a decorative chart.`,
      triggers: "research memo, briefing, source synthesis, literature pass",
    },
    {
      id: "sk-02",
      name: "yard-dispatch",
      title: "Yard Dispatch",
      version: "0.9",
      status: "draft",
      domain: "Operations",
      owner: "Bramble",
      coverage: 61,
      description:
        "How work is ticketed, prioritized, and handed between agents without losing the original ask.",
      body: `Every ticket has an owner, a due hour, and a definition of done.\nDo not create a new ticket when an existing one already covers the work.\nEscalate only after two failed loops or when the ask crosses a policy line.\nWrite handoffs as: context, decision needed, attachments, owner after handoff.`,
      triggers: "dispatch, queue, SLA, handoff, triage",
    },
    {
      id: "sk-03",
      name: "signal-cut",
      title: "Signal Cut",
      version: "2.1",
      status: "published",
      domain: "Research",
      owner: "Pax",
      coverage: 88,
      description:
        "Compress a noisy field into five bullets a principal can read between meetings.",
      body: `Five bullets. No preamble.\nEach bullet: fact, source, why it matters this week.\nSeparate rumor from filing. If it is a rumor, label it.\nEnd with "watch next" — one item only.`,
      triggers: "competitive intel, weekly cut, field notes, scout",
    },
    {
      id: "sk-04",
      name: "desk-voice",
      title: "Desk Voice",
      version: "1.2",
      status: "published",
      domain: "Service",
      owner: "Ivo",
      coverage: 95,
      description:
        "The front-desk register. Short, warm, never cute, never corporate-bland.",
      body: `Answer the question in the first sentence.\nUse the customer's words back to them once, then switch to plain speech.\nDo not thank them for their patience unless we actually delayed them.\nNever invent a policy. Offer a human when the rule is sharp.`,
      triggers: "support reply, concierge, inbound, tone of voice",
    },
    {
      id: "sk-05",
      name: "refund-doctrine",
      title: "Refund Doctrine",
      version: "3.0",
      status: "published",
      domain: "Service",
      owner: "Ivo",
      coverage: 100,
      description:
        "When money moves back. Exact thresholds, exceptions, and the sentence we use.",
      body: `Full refund within 14 days if unused.\nPartial credit after 14 days requires a steward sign-off.\nNever argue with a customer about how they feel. Argue only with the ledger.\nLog the reason code before the money moves.`,
      triggers: "refund, credit, chargeback, billing exception",
    },
    {
      id: "sk-06",
      name: "patch-craft",
      title: "Patch Craft",
      version: "1.0",
      status: "review",
      domain: "Engineering",
      owner: "Ness",
      coverage: 74,
      description:
        "How the house ships a change: smallest patch, tests that fail first, PR that a stranger can review.",
      body: `Reproduce before you patch.\nWrite the failing test with the ticket id in the name.\nDo not refactor a neighbor file \"while you are there.\"\nPR body: why, what, how to prove, what you did not do.`,
      triggers: "pull request, patch, fix, implement ticket",
    },
    {
      id: "sk-07",
      name: "citation-discipline",
      title: "Citation Discipline",
      version: "1.1",
      status: "published",
      domain: "Research",
      owner: "Maren",
      coverage: 90,
      description:
        "What counts as a source, how to mark inference, and when to refuse a claim.",
      body: `Primary over secondary. Named over anonymous.\nIf two sources disagree, show both — do not average them.\nA screenshot is not a source unless the URL and retrieved date sit beside it.\nIf you cannot cite it, it does not ship.`,
      triggers: "cite, source, claim check, footnotes",
    },
    {
      id: "sk-08",
      name: "policy-redline",
      title: "Policy Redline",
      version: "2.0",
      status: "published",
      domain: "Compliance",
      owner: "Maren",
      coverage: 97,
      description:
        "The pass every public sentence takes before it leaves the building.",
      body: `No superlatives we cannot defend in writing.\nNo timelines we do not control.\nNo \"always\" or \"guarantee\" without counsel.\nIf a line is charming and slightly untrue, cut the charm.`,
      triggers: "legal review, redline, public copy, compliance",
    },
  ],
  runs: [
    {
      id: "tr-184",
      agentId: "ag-02",
      skillId: "sk-02",
      kind: "curriculum",
      status: "running",
      score: null,
      started: "07:02",
      note: "Bramble on Yard Dispatch v0.9 — 14 of 20 cases.",
    },
    {
      id: "tr-183",
      agentId: "ag-01",
      skillId: "sk-01",
      kind: "eval",
      status: "passed",
      score: 96,
      started: "Yesterday",
      note: "Memo eval set B. Two deductions for unsourced color.",
    },
    {
      id: "tr-182",
      agentId: "ag-03",
      skillId: "sk-05",
      kind: "drill",
      status: "passed",
      score: 100,
      started: "Yesterday",
      note: "Refund doctrine edge cases. Clean.",
    },
    {
      id: "tr-181",
      agentId: "ag-04",
      skillId: "sk-06",
      kind: "eval",
      status: "failed",
      score: 71,
      started: "Sun",
      note: "Patched a neighbor file. Sent back to Kiln Hall.",
    },
    {
      id: "tr-180",
      agentId: "ag-06",
      skillId: "sk-03",
      kind: "curriculum",
      status: "passed",
      score: 88,
      started: "Sun",
      note: "Signal cut against last week's tape.",
    },
    {
      id: "tr-179",
      agentId: "ag-05",
      skillId: "sk-08",
      kind: "review",
      status: "review",
      score: 94,
      started: "Sat",
      note: "Awaiting steward sign-off on three public lines.",
    },
  ],
  events: [
    { t: "07:04", text: "Bramble entered Kiln Hall for Yard Dispatch drill." },
    { t: "06:51", text: "Ivo closed a refund case under doctrine 3.0." },
    { t: "06:22", text: "Sable published House Research Memo 1.4." },
    { t: "01:18", text: "Ness failed Patch Craft eval — scope creep." },
    { t: "Sun", text: "Pax filed a five-bullet cut on a rival hiring spike." },
    { t: "Sat", text: "Maren opened a redline on the autumn launch copy." },
  ],
};
